---
- hosts: localhost
  remote_user: pi
  gather_facts: no
  tasks:
  - name: Get password
    shell: cat ~/faas_pass.txt
    register: mypass

  - name: POST request for OpenFaaS API that deploys a new image-resize function
    uri:
      url: "http://admin:{{ mypass.stdout }}@{{ hostname }}:31112/system/functions"
      method: POST
      body: "{  \"service\": \"{{ function_name }}\",  \"network\": \"func_functions\",  \"image\": \"{{ image_name }}:latest\",  \"envProcess\": \"python index.py {{ hostname }} {{ minio_user }} {{ minio_pass }} {{ bucket_in }} {{ bucket_out }}\" }"
      body_format: json
      status_code: 202
    register: post_result
    check_mode: false
    ignore_errors: true
    changed_when: false

  - name: PUT request if POST fails (update function deploy) for the image-resize function
    uri:
      url: "http://admin:{{ mypass.stdout }}@{{ node_ip }}:31112/system/functions"
      body: "{  \"service\": \"{{ function_name }}\",  \"network\": \"func_functions\",  \"image\": \"{{ image_name }}:latest\",  \"envProcess\": \"python index.py {{ hostname }} {{ minio_user }} {{ minio_pass }} {{ bucket_in }} {{ bucket_out }}\" }"
      body_format: json
      status_code: 202
    ignore_errors: yes
    when: post_result["non_existent_tag"] is not defined
...