---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Install prerequsiste python3 packages
    pip:
      name:
        - botocore==1.12.236
        - boto==2.49.0
        - boto3==1.9.236
      state: latest

  - name: Create MinIO "{{ bucket_name }}" bucket
    aws_s3:
      bucket: "{{ bucket_name }}"
      mode: create
      aws_access_key: "{{ minio_user }}"
      aws_secret_key: "{{ minio_password }}"
      s3_url: "http://{{ minio_ip }}:9000"
...