---
- hosts: localhost
  remote_user: pi
  gather_facts: no
  tasks:
  - name: Check Kubectl installation and Kubeconfig
    shell: "{{ item }}"
    with_items:
      - export KUBECONFIG=~/.kube/config
      - kubectl config set-context default
      - kubectl create secret docker-registry secret --docker-username=admin --docker-password=XXXX 

# Installation of OpenFaaS
  - name: Install OpenFAAS
    shell: "arkade install openfaas --kubeconfig ~/.kube/config"

  - name: Install faas-cli
    shell: "{{ item }}"
    with_items:
      - arkade get faas-cli
      - curl -SLsf https://cli.openfaas.com | sudo sh
      - kubectl port-forward -n openfaas svc/gateway 8080:8080 &
      - kubectl get secret -n openfaas basic-auth -o jsonpath='{.data.basic-auth-password}' --kubeconfig /home/pi/radonpi/kubeconfig | base64 --decode > ~/faas_pass.txt

  - name: Login FAAS CLI
    shell: "kubectl get secret -n openfaas basic-auth -o jsonpath='{.data.basic-auth-password}' --kubeconfig /home/pi/radonpi/kubeconfig | base64 --decode | faas-cli login --username admin --password-stdin"

  - name: Deploy sample function
    shell: "faas-cli store deploy figlet"

# Installation of MinIO
  - name: Install and run MinIO server
    shell: "{{ item }}"
    with_items:
      - wget https://dl.minio.io/server/minio/release/linux-arm/minio
      - wget https://dl.minio.io/client/mc/release/linux-arm/mc
      - chmod +x mc
      - chmod +x minio
      - sudo ln -s ./minio /usr/bin/minio
      - sudo ln -s ./mc /usr/bin/mc
      - MINIO_ROOT_USER={{ minio_user }} MINIO_ROOT_PASSWORD={{ minio_pass }} ./minio server ~ &
      - mc alias set myminio http://{{ hostname }}:9000 {{ minio_user }} {{ minio_pass }}
...